"use client";

import { useParams } from "next/navigation";
import { AnimatedSection, ErrorState, FeedbackForm, HumanReviewBadge, IntelligenceHalo, InterventionComposer, LoadingState, PageHeader, ReasonList, RiskBadge, SourceBadge, StateCard, StaleDataBanner, SyntheticBadge } from "@/components/ui";
import { formatDate, formatNumber, record, strings, text } from "@/lib/format";
import { useApi } from "@/lib/useApi";

export default function MerchantDetailPage() {
  const params = useParams<{ merchant_id: string }>();
  const merchantId = params.merchant_id;
  const resource = useApi<Record<string, unknown>>(`/api/v1/merchants/${encodeURIComponent(merchantId)}/overview`);
  if (resource.status === "loading") return <LoadingState label="Loading merchant intelligence" />;
  if (resource.status === "error") return <><PageHeader eyebrow="MERCHANT 360" title={merchantId} /><ErrorState message={resource.error} onRetry={resource.retry} /></>;

  const overview = resource.data;
  const identity = record(overview.identity) ?? {};
  const demand = record(overview.demand_context);
  const churn = record(overview.churn_context);
  const benchmark = record(overview.benchmark_context);
  const growth = record(overview.growth_context);
  const dimensions = record(benchmark?.dimension_percentiles) ?? {};
  const churnLimits = strings(churn?.limitations);
  const demandLimits = strings(demand?.limitations);
  const benchmarkLimits = strings(benchmark?.limitations);
  const growthLimits = strings(growth?.limitations);
  const recommendation = text(growth?.recommended_action, "No action supplied by the batch artifact.");

  return <>
    <PageHeader eyebrow="MERCHANT NETWORK / PROFILE" title="Merchant 360" description="One synthetic merchant identity with the intelligence contexts returned by validated batch APIs." actions={<><SyntheticBadge /><HumanReviewBadge /></>} />
    <section className="panel detail-identity">
      <IntelligenceHalo kind="merchant" segments={["Demand", "Inactivity", "Benchmark", "Growth"]} />
      <div className="identity-copy"><p className="eyebrow">ENTITY / {merchantId}</p><h1>{merchantId}</h1><p className="muted">{text(identity.merchant_category)} · {text(identity.business_size)} business</p><div className="identity-tags"><RiskBadge value={text(identity.merchant_status)} /><SourceBadge>Canonical synthetic identity</SourceBadge></div><div className="identity-facts"><div className="identity-fact"><small>District / location</small><strong>{text(identity.district)} · {text(identity.location_id)}</strong></div><div className="identity-fact"><small>Assigned agent</small><strong>{text(identity.assigned_agent_id)}</strong></div><div className="identity-fact"><small>Tenure</small><strong>{identity.merchant_tenure_days === undefined ? "Not supplied" : `${String(identity.merchant_tenure_days)} days`}</strong></div></div></div>
    </section>
    <div className="detail-grid">
      <AnimatedSection><StateCard title="CATEGORY DEMAND OUTLOOK"><div className="panel-body">{demand?.intelligence_available === false ? <ErrorState message="No validated category forecast is available for this merchant category." /> : <><div className="notice notice-warning" style={{ marginBottom: 12 }}><strong>Limitation:</strong> Not a merchant-specific forecast. Represents aggregate category transaction volume.</div><div className="data-pair-grid"><div className="data-pair"><small>Merchant Category</small><strong>{text(demand?.merchant_category)}</strong></div><div className="data-pair"><small>Category Forecast</small><strong>{formatNumber(demand?.predicted_next_day_demand)} BDT</strong></div><div className="data-pair"><small>Forecast Horizon</small><strong>Next day · point forecast</strong></div><div className="data-pair"><small>Forecasting Model</small><strong>XGBoost Regressor</strong></div><div className="data-pair"><small>Demand Level</small><RiskBadge value={text(demand?.demand_level)} /></div><div className="data-pair"><small>Baseline Comparison</small><strong>{demand?.forecast_change_percent === undefined ? "Not supplied" : `${String(demand.forecast_change_percent)}% vs 7d avg`}</strong></div></div><StaleDataBanner asOf={text(demand?.as_of, formatDate(demand?.target_date))} /><ReasonList items={demandLimits} /></>}<FeedbackForm entityType="merchant" entityId={merchantId} capability="merchant_demand" /></div></StateCard></AnimatedSection>
      <AnimatedSection><StateCard title="Inactivity & Churn Hazard"><div className="panel-body">{churn?.intelligence_available === false ? <ErrorState message="No batch churn record is available for this merchant." /> : <><div className="data-pair-grid"><div className="data-pair"><small>Forward Hazard Horizon</small><strong>Forward 30-day inactivity</strong></div><div className="data-pair"><small>Risk Level</small><RiskBadge value={text(churn?.risk_level)} /></div><div className="data-pair"><small>Inactivity Hazard Prob</small><strong>{formatNumber(churn?.churn_probability)}</strong></div><div className="data-pair"><small>Deployed Model</small><strong>LightGBM Classifier (Phase 2 Forward Hazard v2.0)</strong></div></div><div className="notice notice-warning" style={{ marginTop: 15 }}><strong>Evaluation Notice:</strong> Historical rule is defined as <code>days_since_last_txn &gt;= 30</code>. The Phase 2 forward model predicts inactivity in the 30-day window following cutoff without data leakage.</div><ReasonList items={churnLimits} /></>}<FeedbackForm entityType="merchant" entityId={merchantId} capability="merchant_churn" /></div></StateCard></AnimatedSection>
      <AnimatedSection><StateCard title="Peer benchmark"><div className="panel-body">{benchmark?.intelligence_available === false ? <ErrorState message="Benchmark data is not available for this merchant." /> : <><div className="data-pair-grid"><div className="data-pair"><small>Benchmark score</small><strong>{formatNumber(benchmark?.benchmark_score)}</strong></div><div className="data-pair"><small>Performance band</small><RiskBadge value={text(benchmark?.performance_band)} /></div><div className="data-pair"><small>Peer group</small><strong>{text(benchmark?.peer_cohort)}</strong></div><div className="data-pair"><small>Reliability</small><RiskBadge value={text(benchmark?.reliability_level)} /></div><div className="data-pair"><small>Strongest dimension</small><strong>{text(benchmark?.strongest_dimension)}</strong></div><div className="data-pair"><small>Improvement dimension</small><strong>{text(benchmark?.improvement_dimension)}</strong></div></div><div className="percentile-bars" style={{ marginTop: 20 }}>{Object.entries(dimensions).map(([name, value]) => <div className="percentile-row" key={name}><span>{name.replaceAll("_", " ")}</span><div className="percentile-track"><i style={{ width: `${Math.min(100, Math.max(0, Number(value) || 0))}%` }} /></div><strong>{value === null ? "—" : `${String(value)}%`}</strong></div>)}</div><p className="muted text-small" style={{ marginTop: 16 }}>{text(benchmark?.insight)}</p><ReasonList items={benchmarkLimits} /></>}<FeedbackForm entityType="merchant" entityId={merchantId} capability="merchant_benchmark" /></div></StateCard></AnimatedSection>
      <AnimatedSection><StateCard title="Growth recommendation"><div className="panel-body">{growth?.intelligence_available === false ? <ErrorState message="No growth recommendation is available for this merchant." /> : <><div className="data-pair-grid"><div className="data-pair"><small>Opportunity score</small><strong>{formatNumber(growth?.growth_opportunity_score)}</strong></div><div className="data-pair"><small>Priority</small><RiskBadge value={text(growth?.growth_priority)} /></div><div className="data-pair"><small>Recommendation type</small><strong>{text(growth?.recommendation_type)}</strong></div><div className="data-pair"><small>Inactivity context</small><strong>{text(record(growth?.inactivity_context)?.inactivity_level)}</strong></div></div><div className="notice notice-gold" style={{ marginTop: 15 }}>{recommendation}</div><p className="muted text-small" style={{ marginTop: 13 }}>{text(growth?.recommendation_reason)}</p><ReasonList items={growthLimits} /></>}<FeedbackForm entityType="merchant" entityId={merchantId} capability="merchant_growth" /></div></StateCard></AnimatedSection>
      <AnimatedSection><StateCard title="Human action"><div className="panel-body"><div className="notice notice-warning">Proposals are records for authorized human review. They do not execute financial or operational actions.</div><div style={{ marginTop: 17 }}><InterventionComposer targetType="merchant" targetId={merchantId} capability="merchant_growth" recommendation={recommendation} reason={text(growth?.recommendation_reason, "Review the available batch intelligence.")} /></div></div></StateCard></AnimatedSection>
    </div>
  </>;
}
