from fastapi import APIRouter, Depends, Request
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.security.audit import record_audit_event
from app.security.dependencies import require_roles

router = APIRouter()

MODEL_REGISTRY = [
    {
        "capability": "Merchant Demand Forecasting",
        "display_title": "Merchant Category Demand Forecasting",
        "engine_type": "ML: XGBoost Regressor (Preserved)",
        "serving_mode": "batch",
        "horizon": "next_day",
        "forecast_scope": "merchant_category",
        "artifact": "merchant_demand_intelligence_output.csv",
        "version": "1.0",
        "data_version": "2026-09-30-batch",
        "baseline": "Seasonal Naive (7d) & 7-Day Rolling Average",
        "documented_metrics": {
            "test_samples": 390,
            "model_mae": 94618.37,
            "baseline_rolling_7d_mae": 21707.56,
            "baseline_snaive_7d_mae": 28172.45,
            "p10_p90_empirical_coverage_percent": 80.26,
            "target_coverage_percent": 80.0,
        },
        "top_features": [
            {"feature": "value_lag_1d", "importance": 0.32},
            {"feature": "value_mean_7d", "importance": 0.24},
            {"feature": "value_lag_7d", "importance": 0.18},
            {"feature": "daily_txn_count", "importance": 0.12},
            {"feature": "target_day_of_week", "importance": 0.08},
        ],
        "limitations": [
            "Category Demand Outlook: Category-level aggregate volume only; NOT a merchant-specific forecast.",
            "Point forecast skill has high variance compared to 7-day rolling average baseline.",
            "Uncertainty interval [P10, P90] is calibrated via empirical residuals (80.26% coverage).",
        ],
        "synthetic_data": True,
    },
    {
        "capability": "Merchant Churn Prediction",
        "display_title": "Forward-Looking Merchant Churn Prediction",
        "engine_type": "ML: Logistic Regression (Forward-Looking)",
        "serving_mode": "batch",
        "horizon": "30_day_forward_inactivity",
        "forecast_scope": "merchant_level",
        "artifact": "merchant_forward_churn_predictions.csv",
        "version": "2.0-forward-looking",
        "data_version": "2026-08-31-temporal-cutoff",
        "baseline": "LEGACY / HISTORICAL INACTIVITY RULE (days_since_last_txn >= 30)",
        "documented_metrics": {
            "test_roc_auc": 0.8402,
            "test_pr_auc": 0.4266,
            "operational_threshold": 0.35,
            "test_precision": 0.2555,
            "test_recall": 0.8871,
            "test_f1": 0.3968,
            "canonical_merchants_coverage": "5000/5000 (100%)",
            "unscored_merchants": 0,
        },
        "top_features": [
            {"feature": "days_since_last_txn", "importance": 720, "normalized_pct": 28.5},
            {"feature": "txn_count_30d", "importance": 450, "normalized_pct": 17.8},
            {"feature": "txn_velocity_ratio", "importance": 380, "normalized_pct": 15.0},
            {"feature": "txn_count_7d", "importance": 310, "normalized_pct": 12.3},
            {"feature": "active_days_30d", "importance": 260, "normalized_pct": 10.3},
            {"feature": "merchant_tenure_days", "importance": 220, "normalized_pct": 8.7},
            {"feature": "txn_value_30d", "importance": 185, "normalized_pct": 7.3},
        ],
        "threshold_rationale": "Threshold 0.35 captures 88.7% of upcoming churners while maintaining field officer review workload at an actionable 44.3% of the network.",
        "limitations": [
            "Predicts hazard of 0 transactions in the 30 days AFTER cutoff date T.",
            "Features strictly utilize transactions on or before cutoff date T (no future leakage).",
            "The legacy deterministic label was days_since_last_txn >= 30; new Phase 2 model predicts forward 30-day inactivity from cutoff T without leakage.",
        ],
        "synthetic_data": True,
    },
    {
        "capability": "Merchant Benchmarking",
        "engine_type": "PERCENTILE ENGINE",
        "serving_mode": "batch",
        "horizon": "snapshot",
        "artifact": "merchant_benchmark_intelligence_output.csv",
        "version": "1.0",
        "peer_grouping_columns": ["category", "district"],
        "peer_group_size": "Min 10 merchants per peer cohort",
        "percentile_definition": "Empirical CDF percentiles (0-100) across transaction volume, active days, and basket size",
        "fallback_behavior": "If cohort < 10, falls back to category-level national deciles",
        "documented_metrics": {
            "merchants": 5000,
            "mean_benchmark_score": 50.4,
            "reliability_high": 4792,
            "reliability_moderate": 105,
            "reliability_limited": 103,
        },
        "limitations": [
            "Peer-relative percentile engine, not trained ML.",
            "Scores are not probabilities, causal effects, or model accuracy.",
        ],
        "synthetic_data": True,
    },
    {
        "capability": "Merchant Growth Recommendation",
        "engine_type": "RULE ENGINE",
        "serving_mode": "batch",
        "horizon": "snapshot",
        "artifact": "merchant_growth_intelligence_output.csv",
        "version": "1.0",
        "peer_grouping_columns": ["category", "tier"],
        "peer_group_size": "Cohort-level benchmark thresholds",
        "percentile_definition": "Rule-based scoring: 30% gap to peer median, 40% growth velocity, 30% product adoption",
        "fallback_behavior": "National tier medians",
        "documented_metrics": {
            "merchants": 5000,
            "history_available": 4848,
            "insufficient_history": 152,
            "priority_low": 2498,
            "priority_medium": 1252,
            "priority_high": 684,
            "priority_critical": 566,
        },
        "limitations": [
            "Rule/peer decision support, not trained predictive ML.",
            "Growth score is not a probability or causal uplift estimate.",
            "Consequential recommendations require human review.",
        ],
        "synthetic_data": True,
    },
    {
        "capability": "Agent Liquidity Intelligence",
        "engine_type": "ML: LightGBM Regressor (Operational P90 Buffer)",
        "serving_mode": "batch",
        "horizon": "next_day",
        "forecast_scope": "agent_level",
        "artifact": "agent_liquidity_intelligence_output.csv",
        "version": "2.0-cleaned-next-day",
        "data_version": "2026-09-30-hourly-aggregated",
        "baseline": "Lag-1 Cashout & Rolling 7-Day P90",
        "documented_metrics": {
            "test_samples": 12102,
            "point_forecast_mae": 1455.40,
            "point_forecast_r2": -0.00949,
            "p90_pinball_loss": 615.62,
            "empirical_p90_coverage_percent": 89.93,
            "target_p90_coverage_percent": 90.0,
            "shortfall_proxy_rate_percent": 10.07,
            "average_recommended_buffer_bdt": 1999.53,
        },
        "top_features": [
            {"feature": "cashout_mean_7d", "importance": 480},
            {"feature": "cashout_lag_1d", "importance": 410},
            {"feature": "cashout_std_7d", "importance": 360},
            {"feature": "liquidity_limit", "importance": 310},
            {"feature": "txn_value", "importance": 240},
        ],
        "limitations": [
            "Next calendar day only; no hourly or 6/12/24/48-hour paths.",
            "Point forecast skill is weak (R² ≈ -0.009); model is operationalized as a calibrated P90 buffer.",
            "liquidity_limit is a capacity proxy, not live cash.",
            "Risk bands are not shortage probabilities; recommended-cash coverage is not accuracy.",
            "Weak test R-squared; consequential financial actions require human review.",
        ],
        "synthetic_data": True,
    },
    {
        "capability": "Agent Performance Intelligence",
        "display_title": "Agent Performance & Underperformance Intelligence",
        "engine_type": "Rule/percentile engine",
        "serving_mode": "batch",
        "horizon": "30_day_forward_window",
        "forecast_scope": "agent_level",
        "artifact": "agent_performance_intelligence_output.csv",
        "version": "1.0-forward-looking",
        "data_version": "2026-08-31-temporal-cutoff",
        "baseline": "Lag-1 Service Gap Status & District Cohort Baseline",
        "peer_grouping_columns": ["agent_type", "district"],
        "peer_group_size": "Min 8 agents per district-type group",
        "percentile_definition": "Threshold rules: service gap if active days < 5; declining if velocity < 0.5; abnormal if z-score > 3.0",
        "fallback_behavior": "If district group < 8, compares against nationwide agent_type baseline",
        "documented_metrics": {
            "test_samples": 800,
            "test_roc_auc": 0.9358,
            "test_pr_auc": 0.7910,
            "operational_threshold": 0.40,
            "test_precision": 0.5798,
            "test_recall": 0.8625,
            "test_f1": 0.6935,
            "agents_scored": 800,
            "service_gap_flags": 80,
            "declining_agents": 193,
            "emerging_high_performers": 96,
            "abnormal_pattern_flags": 15,
        },
        "top_features": [
            {"feature": "active_days_30d", "importance": 0.3120},
            {"feature": "txn_count_30d", "importance": 0.2280},
            {"feature": "txn_value_30d", "importance": 0.1650},
            {"feature": "commission_30d", "importance": 0.1140},
            {"feature": "txn_velocity_ratio", "importance": 0.0890},
            {"feature": "tenure_days", "importance": 0.0520},
        ],
        "limitations": [
            "Peer-relative operational flags; no Isolation Forest or trained anomaly detector is supplied.",
            "Abnormal activity is not fraud detection.",
            "Consequential actions require human review.",
            "Learned underperformance classifier predicts hazard of dropping below 5 active days or bottom 20% volume in forward 30 days.",
        ],
        "synthetic_data": True,
    },
    {
        "capability": "Location Intelligence",
        "engine_type": "PERCENTILE ENGINE",
        "serving_mode": "batch",
        "horizon": "observed_aggregate_window",
        "forecast_scope": "location_level",
        "artifact": "location_intelligence_output.csv",
        "version": "1.0-spatial-scoring",
        "peer_grouping_columns": ["area_type", "district"],
        "peer_group_size": "120 geographic nodes across 64 districts",
        "percentile_definition": "Weighted composite score: 40% merchant volume density rank + 35% agent coverage gap + 25% footfall proxy rank",
        "fallback_behavior": "Isolated location nodes without neighbors use national area_type decile distributions",
        "documented_metrics": {
            "locations": 120,
            "priority_low": 60,
            "priority_medium": 30,
            "priority_high": 18,
            "priority_critical": 12,
        },
        "limitations": [
            "Relative opportunity index, not trained ML or probability.",
            "No real GPS coordinates or geometry are supplied.",
            "CRITICAL is relative opportunity, not an emergency; expansion requires human review.",
        ],
        "synthetic_data": True,
    },
]


@router.get("/models")
def list_models(
    request: Request,
    user=Depends(require_roles("ADMIN", "JUDGE")),
    session: Session = Depends(get_db),
):
    if user.role == "ADMIN":
        record_audit_event(
            session,
            event_type="PRIVILEGED_ACCESS",
            actor_user_id=user.id,
            subject_type="model_registry",
            subject_id="all",
            correlation_id=getattr(request.state, "correlation_id", None),
            metadata={"operation": "read"},
        )
        session.commit()
    return {"items": MODEL_REGISTRY, "total": len(MODEL_REGISTRY)}