"use client";

import { useParams } from "next/navigation";
import { AlertTriangle, Droplets } from "lucide-react";

import { AnimatedSection, EmptyState, ErrorState, FeedbackForm, HumanReviewBadge, IntelligenceHalo, InterventionComposer, LoadingState, PageHeader, ReasonList, RiskBadge, SourceBadge, StateCard, StaleDataBanner, SyntheticBadge } from "@/components/ui";
import { formatDate, formatNumber, record, strings, text } from "@/lib/format";
import { useApi } from "@/lib/useApi";

export default function AgentDetailPage() {
  const params = useParams<{ agent_id: string }>();
  const agentId = params.agent_id;
  const resource = useApi<Record<string, unknown>>(`/api/v1/agents/${encodeURIComponent(agentId)}/overview`);
  if (resource.status === "loading") return <LoadingState label="Loading agent intelligence" />;
  if (resource.status === "error") return <><PageHeader eyebrow="AGENT 360" title={agentId} /><ErrorState message={resource.error} onRetry={resource.retry} /></>;

  const overview = resource.data;
  const identity = record(overview.identity) ?? {};
  const liquidity = record(overview.liquidity_context);
  const performance = record(overview.performance_context);
  const review = record(overview.operational_review_context);
  const limits = strings(liquidity?.limitations);
  const performanceLimits = strings(performance?.limitations);
  const recommendation = text(liquidity?.recommended_action, "Review validated next-day liquidity context.");

  return <>
    <PageHeader eyebrow="AGENT NETWORK / PROFILE" title="Agent 360" description="Validated next-day liquidity and peer-relative operating signals for one synthetic agent." actions={<><SyntheticBadge /><HumanReviewBadge /></>} />
    <section className="panel detail-identity"><IntelligenceHalo kind="agent" segments={["Liquidity", "Performance", "Review"]} /><div className="identity-copy"><p className="eyebrow">ENTITY / {agentId}</p><h1>{agentId}</h1><p className="muted">{text(identity.agent_type)} agent · {text(identity.district)} · {text(identity.location_id)}</p><div className="identity-tags"><RiskBadge value={text(identity.status)} /><SourceBadge>Canonical synthetic identity</SourceBadge></div><div className="identity-facts"><div className="identity-fact"><small>Operating window</small><strong>{identity.operating_start_hour === undefined ? "Not supplied" : `${String(identity.operating_start_hour)}:00`} – {identity.operating_end_hour === undefined ? "Not supplied" : `${String(identity.operating_end_hour)}:00`}</strong></div><div className="identity-fact"><small>Tenure</small><strong>{identity.agent_tenure_days === undefined ? "Not supplied" : `${String(identity.agent_tenure_days)} days`}</strong></div><div className="identity-fact"><small>Capacity proxy</small><strong>{formatNumber(identity.liquidity_limit_capacity_proxy)}</strong></div></div></div></section>
    <div className="detail-grid">
      <AnimatedSection><StateCard title="Next-day liquidity intelligence"><div className="panel-body">{liquidity?.intelligence_available === false ? <ErrorState message="No validated liquidity result is available for this agent." /> : <><div className="data-pair-grid"><div className="data-pair"><small>Horizon</small><strong>Next day only</strong></div><div className="data-pair"><small>Target date</small><strong>{formatDate(liquidity?.target_date)}</strong></div><div className="data-pair"><small>Predicted cash-out</small><strong>{formatNumber(liquidity?.predicted_next_day_cashout)}</strong></div><div className="data-pair"><small>Recommended cash</small><strong>{formatNumber(liquidity?.recommended_cash)}</strong></div><div className="data-pair"><small>Liquidity stress</small><strong>{liquidity?.liquidity_stress_percent === undefined ? "Not supplied" : `${formatNumber(liquidity.liquidity_stress_percent)}%`}</strong></div><div className="data-pair"><small>Operational band</small><RiskBadge value={text(liquidity?.risk_level)} /></div><div className="data-pair"><small>Capacity proxy</small><strong>{formatNumber(liquidity?.liquidity_limit_capacity_proxy)}</strong></div><div className="data-pair"><small>As of</small><strong>{formatDate(liquidity?.as_of)}</strong></div></div><div className="notice notice-warning" style={{ marginTop: 16 }}>Recommended cash is not model accuracy. Liquidity limit is a capacity proxy, not live wallet cash.</div><StaleDataBanner asOf={formatDate(liquidity?.as_of)} /><ReasonList items={limits} /><div className="panel-footer">Source version: {text(record(liquidity?.model_or_engine_metadata)?.version)} · Batch serving</div></>}<FeedbackForm entityType="agent" entityId={agentId} capability="agent_liquidity" /></div></StateCard></AnimatedSection>
      <AnimatedSection><StateCard title="Performance intelligence"><div className="panel-body">{performance?.intelligence_available === false ? <ErrorState message="No performance summary is available for this agent." /> : <><div className="data-pair-grid"><div className="data-pair"><small>Performance score</small><strong>{formatNumber(performance?.performance_score)}</strong></div><div className="data-pair"><small>Band</small><RiskBadge value={text(performance?.performance_band)} /></div><div className="data-pair"><small>Momentum</small><strong>{formatNumber(performance?.momentum_score)}</strong></div><div className="data-pair"><small>Emerging performer</small><strong>{performance?.emerging_high_performer === undefined ? "Not supplied" : performance.emerging_high_performer ? "Yes" : "No"}</strong></div><div className="data-pair"><small>Declining flag</small><strong>{performance?.declining === undefined ? "Not supplied" : performance.declining ? "Flagged" : "Not flagged"}</strong></div><div className="data-pair"><small>Service gap</small><RiskBadge value={performance?.service_gap === undefined ? "Not supplied" : String(performance.service_gap)} /></div><div className="data-pair"><small>Primary strength</small><strong>{text(performance?.primary_strength)}</strong></div><div className="data-pair"><small>Improvement area</small><strong>{text(performance?.primary_improvement_area)}</strong></div></div><p className="muted text-small" style={{ marginTop: 15 }}>{text(performance?.reason)}</p><ReasonList items={performanceLimits} /></>}<FeedbackForm entityType="agent" entityId={agentId} capability="agent_performance" /></div></StateCard></AnimatedSection>
      <AnimatedSection><StateCard title="Operational review signals"><div className="panel-body">{review ? <><div className="notice notice-warning"><AlertTriangle size={15} /><span>{text(review.statement, "Operational flags are supplied for review only.")}</span></div><div className="identity-tags" style={{ marginTop: 14 }}>{Array.isArray(review.flags) && review.flags.length > 0 ? review.flags.map((flag) => <RiskBadge key={String(flag)} value={String(flag)} />) : <span className="muted text-small">No existing operational activity flags returned.</span>}</div><p className="muted text-small" style={{ marginTop: 15 }}>This is a peer-relative rule signal. No Isolation Forest or fraud conclusion is supplied.</p></> : <EmptyState title="Review signals unavailable" detail="The overview did not include operational review data." />}<FeedbackForm entityType="agent" entityId={agentId} capability="agent_performance" /></div></StateCard></AnimatedSection>
      <AnimatedSection><StateCard title="Human action"><div className="panel-body"><div className="notice notice-warning"><Droplets size={15} /><span>Proposal only. Authorized people review and record workflow decisions; this control does not move money or rebalance cash.</span></div><div style={{ marginTop: 17 }}><InterventionComposer targetType="agent" targetId={agentId} capability="agent_liquidity" recommendation={recommendation} reason="Review the supplied next-day batch context with the agent." /></div></div></StateCard></AnimatedSection>
    </div>
  </>;
}
